name: Java application demo pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v2.3.0
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install dependencies
      run: |
        mvn install
        
    - name: Run CloudDefense SCA
      uses: cdefense/actions/java@master
      with:
        project-name: Java_Github_Action_Pipeline_Demo
        api-key: ${{ secrets.PROD_API_KEY }}
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: SAST Scan
      run: |
        curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz && tar -C /usr/local/bin -xzf /tmp/cd-latest-linux-x64.tar.gz && chmod +x /usr/local/bin/cdefense
        cdefense sast --lang=java --project-name="Java_Github_Action_Pipeline_Demo" --api-key=${{ secrets.PROD_API_KEY }}

    
